export const books = [
  {
    id: 'p-1',
    title: 'Learn Python the Hard Way',
    thumbnail: 'img/learn-python-the-hard-way.jpeg',
    price: 6.75,
    category: 'python',
  },
  {
    id: 'p-2',
    title: 'Dive into Python 3',
    thumbnail: 'img/dive-into-python-3.jpeg',
    price: 7.99,
    category: 'python',
  },
  {
    id: 'p-3',
    title: 'Head First Python',
    thumbnail: 'img/head-first-python.jpeg',
    price: 9.02,
    category: 'python',
  },
  {
    id: 'p-4',
    title: 'Python Crash Course',
    thumbnail: 'img/python-crash-course.jpeg',
    price: 22.00,
    category: 'python',
  },
  {
    id: 'p-5',
    title: 'Effective Python',
    thumbnail: 'img/effective-python.jpeg',
    price: 8.55,
    category: 'python',
  },
  {
    id: 'p-6',
    title: 'Think Python',
    thumbnail: 'img/think-python.jpeg',
    price: 4.75,
    category: 'python',
  },
  {
    id: 'p-7',
    title: 'Python Cookbook',
    thumbnail: 'img/python-cookbook.jpeg',
    price: 11.49,
    category: 'python',
  },
  {
    id: 'p-8',
    title: 'Fluent Python',
    thumbnail: 'img/fluent-python.jpeg',
    price: 6.75,
    category: 'python',
  },
  {
    id: 'j-1',
    title: 'Javascript for Kids',
    thumbnail: 'img/js-for-kids.jpeg',
    price: 6.75,
    category: 'javascript',
  },
  {
    id: 'j-2',
    title: 'Head First Javascript',
    thumbnail: 'img/head-first-javascript.jpeg',
    price: 14.00,
    category: 'javascript',
  },
  {
    id: 'j-3',
    title: 'Javascript Guide',
    thumbnail: 'img/javascript-the-definitive-guide.jpeg',
    price: 16.00,
    category: 'javascript',
  },
  {
    id: 'j-4',
    title: 'Javascript the Good Parts',
    thumbnail: 'img/javascript-the-good-parts.jpeg',
    price: 12.75,
    category: 'javascript',
  },
  {
    id: 'j-5',
    title: 'Javascript & Jquery',
    thumbnail: 'img/javascript-and-jquery.jpeg',
    price: 21.00,
    category: 'javascript',
  },
  {
    id: 'j-6',
    title: 'You Don\'t Know JS',
    thumbnail: 'img/you-don-t-know-js.jpeg',
    price: 6.75,
    category: 'javascript',
  },
  {
    id: 'j-7',
    title: 'Eloquent Javascript',
    thumbnail: 'img/eloquent-javascript.jpeg',
    price: 9.75,
    category: 'javascript',
  },
  {
    id: 'j-8',
    title: 'Programming JS Apps',
    thumbnail: 'img/programming-javascript-applications.jpeg',
    price: 11.35,
    category: 'javascript',
  },

];
